# Site
repository: Git repository where your resume will be hosted, only required if you are hosting on GitHub (eg. sproogen/modern-resume-theme)
# favicon: Directory of your favicon (eg. images/favicon.ico)(optional)

# Content configuration version
version: 2

# Personal info
name: 황지훈
title: 백엔드 개발자
email: wlgns6147@naver.com
# email_title: Email (Email title override)
# phone: Your phone number (optional)
# phone_title: Phone (Phone title override)
# website: Your website (eg. https://google.com)(optional)
# website_title: Web (Website title override)

# Dark Mode (true/false/never)
darkmode: true

# Social links
# twitter_username: jekyllrb
# github_username:  jekyll
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: jekyll
# linkedin_username: jekyll
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: jekyll
# orcid_username: 0000-0000-0000-0000
# googlescholar_username: D847cGsAAAAJ

# Additional icon links
# additional_links:
# - title: Link name
#   icon: Font Awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&s=brands&m=free)
#   url: Link url (eg. https://google.com)
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&s=brands&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
about_title: About Me 1 (Use this to override about section title)
about_profile_image: Directory of profile image (eg. images/profile.jpg)
about_content: | # this will include new lines to allow paragraphs
  Java & Spring / Oracle & MariaDB 기반의 7년차 백엔드 개발자로 __1금융권 퇴직연금 서비스__ 개발, __임상 데이터 연구 & 분석(Clinical Data Warehouse) 플랫폼__ 개발 및 인프라 구축 등을 해왔습니다.
  개인이 하고 싶은 일 보다는 회사와 팀에 도움이 되는 개발을 해야한다는 생각에 ... <mark>팀원과 팀의 성장</mark> 등을 주요 업무로 하고 있습니다.
  
# xtrabackup, pt-online-schema-change, MHA를 활용한 MySQL 운영, Ansible을 이용한 IDC 인프라 운영을 해오기도 했습니다.
# 테스트 코드 작성을 당연하게 생각하여 전 직장 시스템의 경우 2500개의 테스트 케이스가 하루에도 수십번 수행되는 환경을 구성하였습니다.
# 현재는 CTO로 사업과 제품의 방향성을 고려하여 채용, 시스템 설계, 팀 매니징, <mark>팀원과 팀의 성장<mark> 등을 주요 업무로 하고 있습니다.

content:
  - title: Experience
    layout: list
    content:
      - layout: left
        title: 더존비즈온
        link: https://www.douzone.com/
        sub_title: Java & Spring 백엔드 개발자
        caption: 2021.02 ~ 현재
        quote: >
          임상 데이터 연구 & 분석 플랫폼
        description: | # this will include new lines to allow paragraphs
          업무 정리 후 작성

      - layout: left
        title: 조이앤비즈
        link: http://www.joynbiz.co.kr/
        sub_title: Java 백엔드 개발자
        caption: 2018.11 ~ 2021.02
        quote: >
          1금융권 퇴직연금 서비스
        description: | # this will include new lines to allow paragraphs
          - IBK기업은행 퇴직연금 재구축 2018.11 ~ 2019.03 (5개월)
          - KB국민은행 THE K 퇴직연금 고도화 2019.04 ~ 2020.02 (10개월)
          - KB국민은행 퇴직연금 SM 2020.03 ~ 2020.09 (6개월)
          - KB국민은행 퇴직연금 고도화 2020.10 ~ 2021.02 (4개월)

  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        border: weak  # Value of `weak` will display a weak border below this item. # Any 
                      # other value (or no value) means no border will be displayed
        title: Project name
        link: Link to project (eg. sproogen.github.io/modern-resume-theme)(optional)
        link_text: Link Text
        additional_links:
          - title:  Github page for project (eg. sproogen/modern-resume-theme)
            icon: fab fa-github
            url: Link to project (eg. sproogen.github.io/modern-resume-theme)(optional)
          - title:  Github page for project (eg. sproogen/modern-resume-theme)
            icon: fab fa-github
            url: Link to project (eg. sproogen.github.io/modern-resume-theme)(optional)
        quote: >
          Short overview of the project (optional)
        description: | # this will include new lines to allow paragraphs
          Description about the work on/with the project

  - title: Skill
    layout: list
    quote: >
      현재 업무에 사용중 혹은 사용했던 기술들입니다.
    content:
      - layout: left
        title: Backend
        description: | # this will include new lines to allow paragraphs
          - Java, Maven
          - IntelliJ

        title: DevOps
        quote: >
          현재 업무에 사용중 혹은 사용했던 기술들입니다.
        description: | # this will include new lines to allow paragraphs
          - Oracle, MariaDB
          - Tomcat
          - Orange, Data Grip

        title: Frontend
        quote: >
          현재 업무에 사용중 혹은 사용했던 기술들입니다.
        description: | # this will include new lines to allow paragraphs
          - React, Npm, Node
          - Visual Studio Code

  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      - 나는 누구
      - 여긴 어디

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
# theme: modern-resume-theme (Use this is you are hosting your resume yourself)
# remote_theme: sproogen/modern-resume-theme (Use this if you are hosting your resume on GitHub)

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag

exclude : [
  "Gemfile",
  "Gemfile.lock",
  "node_modules",
  "vendor/bundle/",
  "vendor/cache/",
  "vendor/gems/",
  "vendor/ruby/",
  "lib/",
  "scripts/",
  "docker-compose.yml",
  ]
